"""add lineas_telefonicas table

Revision ID: b0e0159bc517
Revises: 27267d025f38
Create Date: 2024-06-11 09:47:42.314678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0e0159bc517'
down_revision: Union[str, None] = '27267d025f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineas_telefonicas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.String(length=20), nullable=True),
        sa.Column('operador', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_lineas_telefonicas_id'), 'lineas_telefonicas', ['id'], unique=False)
    op.create_index(op.f('ix_lineas_telefonicas_numero'), 'lineas_telefonicas', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineas_telefonicas_numero'), table_name='lineas_telefonicas')
    op.drop_index(op.f('ix_lineas_telefonicas_id'), table_name='lineas_telefonicas')
    op.drop_table('lineas_telefonicas')
    # ### end Alembic commands ###