"""Initial migration

Revision ID: ccfb4ca42c6d
Revises: 
Create Date: 2024-06-09 08:51:58.020503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfb4ca42c6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_votacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codificacion_vieja_cv', sa.Integer(), nullable=True),
    sa.Column('codificacion_nueva_cv', sa.Integer(), nullable=True),
    sa.Column('condicion', sa.Integer(), nullable=True),
    sa.Column('codigo_estado', sa.Integer(), nullable=True),
    sa.Column('codigo_municipio', sa.Integer(), nullable=True),
    sa.Column('codigo_parroquia', sa.Integer(), nullable=True),
    sa.Column('nombre_cv', sa.String(length=255), nullable=True),
    sa.Column('direccion_cv', sa.String(length=755), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_votacion_id'), 'centros_votacion', ['id'], unique=False)
    op.create_table('electores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letra_cedula', sa.String(length=1), nullable=True),
    sa.Column('numero_cedula', sa.BigInteger(), nullable=True),
    sa.Column('p_apellido', sa.String(length=35), nullable=True),
    sa.Column('s_apellido', sa.String(length=35), nullable=True),
    sa.Column('p_nombre', sa.String(length=35), nullable=True),
    sa.Column('s_nombre', sa.String(length=35), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('codigo_estado', sa.Integer(), nullable=True),
    sa.Column('codigo_municipio', sa.Integer(), nullable=True),
    sa.Column('codigo_parroquia', sa.Integer(), nullable=True),
    sa.Column('codigo_centro_votacion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electores_id'), 'electores', ['id'], unique=False)
    op.create_table('geograficos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_estado', sa.Integer(), nullable=True),
    sa.Column('codigo_municipio', sa.Integer(), nullable=True),
    sa.Column('codigo_parroquia', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=35), nullable=True),
    sa.Column('municipio', sa.String(length=35), nullable=True),
    sa.Column('parroquia', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geograficos_id'), 'geograficos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geograficos_id'), table_name='geograficos')
    op.drop_table('geograficos')
    op.drop_index(op.f('ix_electores_id'), table_name='electores')
    op.drop_table('electores')
    op.drop_index(op.f('ix_centros_votacion_id'), table_name='centros_votacion')
    op.drop_table('centros_votacion')
    # ### end Alembic commands ###
