"""Add unique constraint and index to cedula in tickets

Revision ID: f81482e543c0
Revises: 0a28c1291433
Create Date: 2024-06-10 09:39:45.785752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81482e543c0'
down_revision: Union[str, None] = '0a28c1291433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tickets', ['cedula'])
    op.create_index('ix_ticket_cedula', 'tickets', ['cedula'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_cedula', table_name='tickets')
    op.drop_constraint(None, 'tickets', type_='unique')
    # ### end Alembic commands ###